name: features_maps
description: Maps feature (abstractions, screens placeholder)
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

dev_dependencies:
  flutter_lints: ^4.0.0
