name: design_system
description: Design System (Material 3, themes, widgets dùng chung)
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
