name: core
description: Core utilities for FoodWalk (env, http, error handling)
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_secure_storage: ^8.0.0
  riverpod: ^2.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
